"""
main.py — DRIS//CORE  Free Transcription Server
================================================
Generated by system_init.py.  Safe to regenerate at any time.

100% free — no API keys required.
  Transcription : Google Speech Recognition (SpeechRecognition library)
  Translation   : Google Translate          (deep-translator library)
  Audio decode  : pydub + ffmpeg            (webm/ogg/wav from browser)

WebSocket:  ws://localhost:8000/ws/transcribe

Protocol
--------
Client → Server  (JSON text):
  {"action":"start","target_lang":"nl","source_lang":"en"}
  {"action":"stop"}

Client → Server  (binary):
  Raw audio blob from browser MediaRecorder (webm / ogg / wav)

Server → Client  (JSON text):
  {"type":"status",      "message":"..."}
  {"type":"transcript",  "original":"...","timestamp":0.0}
  {"type":"translation", "text":"...","lang":"nl","start":0.0,"end":4.0}
  {"type":"srt_ready",   "filename":"...","content":"..."}
  {"type":"error",       "message":"..."}
"""

import asyncio, io, json, os, time, uuid
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware

SUPPORTED_LANGS = {"nl": "Dutch", "fr": "French", "it": "Italian", "es": "Spanish"}


@asynccontextmanager
async def lifespan(app):
    print("\n┌────────────────────────────────────────────────┐")
    print("│  DRIS//CORE  —  Free Transcription Engine      │")
    print("│  WS: ws://localhost:8000/ws/transcribe         │")
    print("│  Engine: SpeechRecognition + deep-translator   │")
    print("│  No API keys required.                         │")
    print("└────────────────────────────────────────────────┘\n")
    yield


app = FastAPI(title="DRIS//CORE Transcription API (Free)", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], allow_methods=["*"], allow_headers=["*"],
)


@app.get("/health")
def health():
    return {"status": "ok", "engine": "SpeechRecognition+GoogleTranslate(free)"}


# ── Audio conversion: browser webm/ogg → 16 kHz mono WAV ─────────────────────

def _to_wav_bytes(audio_bytes: bytes) -> bytes:
    """
    Convert arbitrary audio blob (webm, ogg, mp4, wav) to 16 kHz mono WAV.
    Falls back to raw bytes if pydub / ffmpeg is unavailable — SR can still
    handle a native WAV payload from the browser.
    """
    try:
        from pydub import AudioSegment
        seg = AudioSegment.from_file(io.BytesIO(audio_bytes))
        seg = seg.set_frame_rate(16000).set_channels(1)
        buf = io.BytesIO()
        seg.export(buf, format="wav")
        return buf.getvalue()
    except Exception:
        return audio_bytes   # hope it is already WAV


# ── Transcription: SpeechRecognition → Google free Speech API ────────────────

def _transcribe_sync(audio_bytes: bytes, language: str = "en") -> str:
    import speech_recognition as sr

    recognizer = sr.Recognizer()
    wav_bytes   = _to_wav_bytes(audio_bytes)

    # BCP-47 codes for the Google SR API
    lang_map = {
        "en": "en-US", "nl": "nl-NL", "fr": "fr-FR",
        "it": "it-IT", "es": "es-ES",
    }
    bcp47 = lang_map.get(language, language)

    try:
        with sr.AudioFile(io.BytesIO(wav_bytes)) as src:
            audio = recognizer.record(src)
        return recognizer.recognize_google(audio, language=bcp47)
    except sr.UnknownValueError:
        return ""          # silence or unintelligible — normal, not an error
    except sr.RequestError as exc:
        raise RuntimeError(f"Google SR API unreachable: {exc}")
    except Exception as exc:
        raise RuntimeError(f"Transcription error: {exc}")


# ── Translation: deep-translator → Google Translate (free) ───────────────────

def _translate_sync(text: str, target_lang: str) -> str:
    if not text.strip():
        return ""
    try:
        from deep_translator import GoogleTranslator
        return GoogleTranslator(source="auto", target=target_lang).translate(text)
    except Exception as exc:
        raise RuntimeError(f"Translation error: {exc}")


# ── SRT helpers ───────────────────────────────────────────────────────────────

def _srt_ts(seconds: float) -> str:
    total_ms = int(seconds * 1000)
    ms = total_ms % 1000
    s  = (total_ms // 1000) % 60
    m  = (total_ms // 60000) % 60
    h  = total_ms // 3600000
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def _build_srt(segments: list) -> str:
    blocks = []
    for seg in segments:
        idx   = seg["index"]
        start = _srt_ts(seg["start"])
        end   = _srt_ts(seg["end"])
        text  = seg["text"]
        blocks.append("{}
{} --> {}
{}
".format(idx, start, end, text))
    return "
".join(blocks)


# ── WebSocket endpoint ────────────────────────────────────────────────────────

@app.websocket("/ws/transcribe")
async def ws_transcribe(websocket: WebSocket):
    await websocket.accept()

    session_id   = str(uuid.uuid4())[:8]
    source_lang  = "en"
    target_lang  = "nl"
    active       = False
    srt_segments: list = []
    srt_index    = 1
    chunk_offset = 0.0
    CHUNK_SEC    = 4.0   # MediaRecorder timeslice on the browser side

    async def send(payload: dict) -> None:
        await websocket.send_text(json.dumps(payload))

    await send({"type": "status", "message": f"GHOST> SESSION {session_id} — READY"})

    try:
        while True:
            message = await websocket.receive()

            # ── JSON command ──────────────────────────────────────────────────
            if "text" in message:
                msg = json.loads(message["text"])

                if msg.get("action") == "start" and not active:
                    source_lang  = msg.get("source_lang", "en")
                    target_lang  = msg.get("target_lang", "nl")
                    active       = True
                    srt_segments = []
                    srt_index    = 1
                    chunk_offset = 0.0
                    lang_name    = SUPPORTED_LANGS.get(target_lang, target_lang).upper()
                    await send({
                        "type"   : "status",
                        "message": f"GHOST> ON-AIR \u25b6  EN \u2192 {lang_name}",
                    })

                elif msg.get("action") == "stop" and active:
                    active      = False
                    srt_content = _build_srt(srt_segments)
                    ts          = time.strftime("%Y-%m-%dT%H%M%S")
                    filename    = f"{ts}_{session_id}_{target_lang}.srt"
                    exports     = Path("exports")
                    exports.mkdir(exist_ok=True)
                    (exports / filename).write_text(srt_content, encoding="utf-8")
                    await send({"type": "srt_ready",  "filename": filename, "content": srt_content})
                    await send({"type": "status", "message": "GHOST> STANDBY \u25fc  Session closed."})

            # ── Binary audio chunk from browser MediaRecorder ─────────────────
            elif "bytes" in message:
                if not active:
                    continue

                audio_bytes = message["bytes"]
                if not audio_bytes or len(audio_bytes) < 200:
                    continue   # too small — discard

                seg_start     = chunk_offset
                seg_end       = chunk_offset + CHUNK_SEC
                chunk_offset += CHUNK_SEC

                loop = asyncio.get_event_loop()

                # Transcription runs in the default thread-pool (blocking I/O)
                try:
                    transcript = await loop.run_in_executor(
                        None, _transcribe_sync, audio_bytes, source_lang,
                    )
                except Exception as exc:
                    await send({"type": "error", "message": f"SR: {exc}"})
                    continue

                if not transcript:
                    continue   # silence — skip translation

                await send({
                    "type"     : "transcript",
                    "original" : transcript,
                    "timestamp": round(seg_start, 2),
                })

                # Translation
                try:
                    translation = await loop.run_in_executor(
                        None, _translate_sync, transcript, target_lang,
                    )
                except Exception as exc:
                    await send({"type": "error", "message": f"Translate: {exc}"})
                    translation = transcript   # fall back to source text

                if translation:
                    seg_id = str(uuid.uuid4())[:8]
                    await send({
                        "type"      : "translation",
                        "text"      : translation,
                        "lang"      : target_lang,
                        "start"     : round(seg_start, 3),
                        "end"       : round(seg_end,   3),
                        "segment_id": seg_id,
                    })
                    srt_segments.append({
                        "index": srt_index,
                        "start": seg_start,
                        "end"  : seg_end,
                        "text" : translation,
                    })
                    srt_index += 1

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        try:
            await send({"type": "error", "message": str(exc)})
        except Exception:
            pass
